### ISSUE TITLE
HA 2024.1.3 - Integration is broken

### ISSUE THREAD

**Issue by darkman242** [dala318/python_poollab#24]
After updating HomeAssistant to version 2024.1.3 (12.01.2004), the integration cannot retrieve data - entities no longer available.

-------------------------------------------------------------------
Logger: homeassistant.setup
Source: setup.py:403
First occurred: 12. Januar 2024 um 22:00:33 (2 occurrences)
Last logged: 10:24:00

Unable to prepare setup for platform 'poollab.sensor': Platform not found (Exception importing custom_components.poollab.sensor).

-------------------------------------------------------------------
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 12. Januar 2024 um 22:00:33 (2 occurrences)
Last logged: 10:24:00

Unexpected exception importing platform custom_components.poollab.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/poollab/sensor.py", line 46, in <module>
    class MeasurementSensor(CoordinatorEntity, SensorEntity):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_unique_id in subclass

**Comment by coyote1** [comment]
Same here

**Comment by Redounder** [comment]
Same here, integration has broken

**Comment by byselcuq** [comment]
HA has been unavailable since Update 2024.1.3. We kindly ask the developer to check.

**Comment by dala318** [comment]
Yes, realized so myself, it seem it has a bunch of property functions defined that overrides some native attributes and this is no longer allowed.
Solved the first one in above pull-request bot are many more and all are not as easy to solve, will have to read in on what attributes/properties to define in sub-class to correctly make the entity pull the values to the public interface.

**Comment by dala318** [comment]
Solved by #26 and included in release https://github.com/dala318/python_poollab/releases/tag/v1.0.2
